### ISSUE TITLE
Error when running Test-ADFS2AADOnPremRPTrustSet -RPXMLFileDirectory "C:\adfs\apps"

### ISSUE THREAD

**Issue by JanSCilliers** [AzureAD/Deployment-Plans#6]
I am getting prompted for paramaters when running: Test-ADFS2AADOnPremRPTrustSet -RPXMLFileDirectory "C:\adfs\apps"

RulesetName:
KnownRules:
ResultTypeIfUnknownPattern:

So no csv exports is occurring.

**Comment by JanSCilliers** [comment]
Ignore,  I was able to get it to work.

**Comment by hmcmtg** [comment]
I'm getting the same prompt. What did you do to get it to work?
